//
//  CMGContentSource.m
//  logText
//
//  Created by Matthijs Gates on 8/11/18.
//  Copyright © 2018 Matthijs Gates. All rights reserved.
//

#import "MGContentSource.h"

typedef void (^taskBlock)(NSTimer *);
static NSTimer * createPeriodicTask(NSTimeInterval intervalMilliseconds, taskBlock block) {
	NSTimeInterval seconds = intervalMilliseconds / 1000.0;
	return [NSTimer scheduledTimerWithTimeInterval:seconds repeats:TRUE block:block];
}

@interface MGContentSource()
+ (NSArray<NSString *> *) content;
@end

@implementation MGContentSource
{
	NSTimer * 	_timer;
    NSUInteger 	_currentIndex;
}

- (void) start:(NSTimeInterval) intervalMilliseconds {
	assert(intervalMilliseconds > 0);
	_timer = createPeriodicTask(intervalMilliseconds, ^(NSTimer * timer) {
		assert(self->_currentIndex < [MGContentSource content].count);
		[self->_delegate emit:[MGContentSource content][self->_currentIndex]];
		
		//  advance for the next iteration
		self->_currentIndex = (self->_currentIndex + 1) % [MGContentSource content].count;
	});
}

- (void) stop {
    _timer = nil;
}

+ (NSArray<NSString *> *) content {
    return @[
       @"https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss",
       @"",
       @"Johann Carl Friedrich Gauss was born on 30 April 1777 in Brunswick (Braunschweig), in ",
       @"the Duchy of Brunswick-Wolfenbüttel (now part of Lower Saxony, Germany), to poor, ",
       @"working-class parents.[3] His mother was illiterate and never recorded the date of his ",
       @"birth, remembering only that he had been born on a Wednesday, eight days before the ",
       @"Feast of the Ascension (which occurs 39 days after Easter). Gauss later solved this ",
       @"puzzle about his birthdate in the context of finding the date of Easter, deriving ",
       @"methods to compute the date in both past and future years.[4] He was christened and ",
       @"confirmed in a church near the school he attended as a child.[5]",
       @"",
       @"Gauss was a child prodigy. In his memorial on Gauss, Wolfgang Sartorius von ",
       @"Waltershausen says that when Gauss was barely three years old he corrected a math ",
       @"error his father made; and that when he was seven, he confidently solved an arithmetic ",
       @"series problem faster than anyone else in his class of 100 students.[6] Many versions ",
       @"of this story have been retold since that time with various details regarding what the ",
       @"series was - the most frequent being the classical problem of adding all the integers ",
       @"from 1 to 100.[7][8][9] There are many other anecdotes about his precocity while a ",
       @"toddler, and he made his first groundbreaking mathematical discoveries while still a ",
       @"teenager. He completed his magnum opus, Disquisitiones Arithmeticae, in 1798, at the ",
       @"age of 21—though it was not published until 1801. This work was fundamental in ",
       @"consolidating number theory as a discipline and has shaped the field to the present ",
       @"day.",
       @"",
       @"Gauss's intellectual abilities attracted the attention of the Duke of Brunswick,[7][2] ",
       @"who sent him to the Collegium Carolinum (now Braunschweig University of ",
       @"Technology),[7] which he attended from 1792 to 1795,[10] and to the University of ",
       @"Göttingen from 1795 to 1798.[11] While at university, Gauss independently rediscovered ",
       @"several important theorems.[12] His breakthrough occurred in 1796 when he showed that ",
       @"a regular polygon can be constructed by compass and straightedge if the number of its ",
       @"sides is the product of distinct Fermat primes and a power of 2.[13] This was a major ",
       @"discovery in an important field of mathematics; construction problems had occupied ",
       @"mathematicians since the days of the Ancient Greeks, and the discovery ultimately led ",
       @"Gauss to choose mathematics instead of philology as a career. Gauss was so pleased ",
       @"with this result that he requested that a regular heptadecagon be inscribed on his ",
       @"tombstone. The stonemason declined, stating that the difficult construction would ",
       @"essentially look like a circle.[14]",
       @"",
       @"The year 1796 was most productive for both Gauss and number theory. He discovered a ",
       @"construction of the heptadecagon on 30 March.[11][15] He further advanced modular ",
       @"arithmetic, greatly simplifying manipulations in number theory. On 8 April he became ",
       @"the first to prove the quadratic reciprocity law. This remarkably general law allows ",
       @"mathematicians to determine the solvability of any quadratic equation in modular ",
       @"arithmetic. The prime number theorem, conjectured on 31 May, gives a good ",
       @"understanding of how the prime numbers are distributed among the integers.",
       @"",
       @"Gauss also discovered that every positive integer is representable as a sum of at ",
       @"most three triangular numbers on 10 July and then jotted down in his diary the note: ",
       @"ΕΥΡΗΚΑ! num = Δ + Δ' + Δ. On 1 October he published a result on the number of ",
       @"solutions of polynomials with coefficients in finite fields, which 150 years later ",
       @"led to the Weil conjectures.",
       @"",
       @"In 1801, Gauss announced that he had calculated the orbit of an asteroid by the name ",
       @"of Ceres.[11] He also allowed some of his genius to be made public with the ",
       @"publication of Disquisitiones Arithmeticae,[11] and consequently gained widespread ",
       @"fame.[11]",
       @"",
       @"Marriage and children[edit]",
       @"On 9 October 1805,[16] Gauss married Johanna Osthoff (1780–1809), and had a son and a ",
       @"daughter with her.[16][17] Johanna died on 11 October 1809,[16][17][18] and her most ",
       @"recent child, Louis, died the following year.[16] He then married Minna Waldeck ",
       @"(1788–1831)[16][17] on 4 August 1810,[16] and had three more children.[17] Gauss was ",
       @"never quite the same without his first wife, so he, just like his father, grew to ",
       @"dominate his children.[17] Minna Waldeck died on 12 September 1831.[16][17]",
       @"",
       @"Later years and death[edit]",
       @"",
       @"Gauss on his deathbed (1855)",
       @"",
       @"Gauss's gravesite at Albani Cemetery in Göttingen, Germany",
       @"Gauss remained mentally active into his old age, even while suffering from gout and ",
       @"general unhappiness.[19] For example, at the age of 62, he taught himself Russian.[19]",
       @"",
       @"In 1840, Gauss published his influential Dioptrische Untersuchungen,[20] in which he ",
       @"gave the first systematic analysis on the formation of images under a paraxial ",
       @"approximation (Gaussian optics).[21] Among his results, Gauss showed that under a ",
       @"paraxial approximation an optical system can be characterized by its cardinal ",
       @"points[22] and he derived the Gaussian lens formula.[23]",
       @"",
       @"In 1845, he became an associated member of the Royal Institute of the Netherlands; ",
       @"when that became the Royal Netherlands Academy of Arts and Sciences in 1851, he ",
       @"joined as a foreign member.[24]",
       @"",
       @"In 1854, Gauss selected the topic for Bernhard Riemann's Habilitationsvortrag, Über ",
       @"die Hypothesen, welche der Geometrie zu Grunde liegen (habilitation lecture About the ",
       @"hypotheses that underlie Geometry).[25] On the way home from Riemann's lecture, Weber ",
       @"reported that Gauss was full of praise and excitement.[26]",
       @"",
       @"On 23 February 1855, Gauss died of a heart attack in Göttingen (then Kingdom of ",
       @"Hanover and now Lower Saxony);[3][19] he is interred in the Albani Cemetery there. ",
       @"Two people gave eulogies at his funeral: Gauss's son-in-law Heinrich Ewald, and ",
       @"Wolfgang Sartorius von Waltershausen, who was Gauss's close friend and biographer. ",
       @"Gauss's brain was preserved and was studied by Rudolf Wagner, who found its mass to ",
       @"be slightly above average, at 1,492 grams, and the cerebral area equal to 219,588 ",
       @"square millimeters[27] (340.362 square inches). Highly developed convolutions were ",
       @"also found, which in the early 20th century were suggested as the explanation of his ",
       @"genius.[28]",
       @"",
       @"Religious views[edit]",
       @"Gauss was a Lutheran Protestant, a member of the St. Albans Evangelical Lutheran ",
       @"church in Göttingen.[29] Potential evidence that Gauss believed in God comes from his ",
       @"response after solving a problem that had previously defeated him: Finally, two days ",
       @"ago, I succeeded—not on account of my hard efforts, but by the grace of the Lord.[30] ",
       @"One of his biographers, G. Waldo Dunnington, described Gauss's religious views as ",
       @"follows:",
       @"",
       @"For him science was the means of exposing the immortal nucleus of the human soul. In ",
       @"the days of his full strength, it furnished him recreation and, by the prospects ",
       @"which it opened up to him, gave consolation. Toward the end of his life, it brought ",
       @"him confidence. Gauss's God was not a cold and distant figment of metaphysics, nor a ",
       @"distorted caricature of embittered theology. To man is not vouchsafed that fullness ",
       @"of knowledge which would warrant his arrogantly holding that his blurred vision is ",
       @"the full light and that there can be none other which might report the truth as does ",
       @"his. For Gauss, not he who mumbles his creed, but he who lives it, is accepted. He ",
       @"believed that a life worthily spent here on earth is the best, the only, preparation ",
       @"for heaven. Religion is not a question of literature, but of life. God's revelation ",
       @"is continuous, not contained in tablets of stone or sacred parchment. A book is ",
       @"inspired when it inspires. The unshakeable idea of personal continuance after death, ",
       @"the firm belief in a last regulator of things, in an eternal, just, omniscient, ",
       @"omnipotent God, formed the basis of his religious life, which harmonized completely ",
       @"with his scientific research.[31]",
       @"",
       @"Apart from his correspondence, there are not many known details about Gauss's ",
       @"personal creed. Many biographers of Gauss disagree about his religious stance, with ",
       @"Bühler and others considering him a deist with very unorthodox views,[32][33][34] ",
       @"while Dunnington (though admitting that Gauss did not believe literally in all ",
       @"Christian dogmas and that it is unknown what he believed on most doctrinal and ",
       @"confessional questions) points out that he was, at least, a nominal Lutheran.[35]",
       @"",
       @"In connection to this, there is a record of a conversation between Rudolf Wagner and ",
       @"Gauss, in which they discussed William Whewell's book Of the Plurality of Worlds. In ",
       @"this work, Whewell had discarded the possibility of existing life in other planets, ",
       @"on the basis of theological arguments, but this was a position with which both Wagner ",
       @"and Gauss disagreed. Later Wagner explained that he did not fully believe in the ",
       @"Bible, though he confessed that he envied those who were able to easily ",
       @"believe.[32][36] This later led them to discuss the topic of faith, and in some other ",
       @"religious remarks, Gauss said that he had been more influenced by theologians like ",
       @"Lutheran minister Paul Gerhardt than by Moses.[37] Other religious influences ",
       @"included Wilhelm Braubach, Johann Peter Süssmilch, and the New Testament.[38]",
       @"",
       @"Dunnington further elaborates on Gauss's religious views by writing:",
       @"",
       @"Gauss's religious consciousness was based on an insatiable thirst for truth and a ",
       @"deep feeling of justice extending to intellectual as well as material goods. He ",
       @"conceived spiritual life in the whole universe as a great system of law penetrated by ",
       @"eternal truth, and from this source he gained the firm confidence that death does not ",
       @"end all.[39]",
       @"",
       @"Gauss declared he firmly believed in the afterlife, and saw spirituality as something ",
       @"essentially important for human beings.[40] He was quoted stating: The world would be ",
       @"nonsense, the whole creation an absurdity without immortality,[41] and for this ",
       @"statement he was severely criticized by the atheist Eugen Dühring who judged him as a ",
       @"narrow superstitious man.[42]",
       @"",
       @"Though he was not a church-goer,[43] Gauss strongly upheld religious tolerance, ",
       @"believing that one is not justified in disturbing another's religious belief, in ",
       @"which they find consolation for earthly sorrows in time of trouble.[2] When his son ",
       @"Eugene announced that he wanted to become a Christian missionary, Gauss approved of ",
       @"this, saying that regardless of the problems within religious organizations, ",
       @"missionary work was a highly honorable task.[44]",
       @"",
       @"Family[edit]",
       @"",
       @"Gauss's daughter Therese (1816–1864)",
       @"Gauss's personal life was overshadowed by the early death of his first wife, Johanna ",
       @"Osthoff, in 1809, soon followed by the death of one child, Louis. Gauss plunged into ",
       @"a depression from which he never fully recovered. He married again, to Johanna's best ",
       @"friend, Friederica Wilhelmine Waldeck, commonly known as Minna. When his second wife ",
       @"died in 1831 after a long illness,[45] one of his daughters, Therese, took over the ",
       @"household and cared for Gauss for the rest of his life. His mother lived in his house ",
       @"from 1817 until her death in 1839.[2]",
       @"",
       @"Gauss had six children. With Johanna (1780–1809), his children were Joseph ",
       @"(1806–1873), Wilhelmina (1808–1846) and Louis (1809–1810). With Minna Waldeck he also ",
       @"had three children: Eugene (1811–1896), Wilhelm (1813–1879) and Therese (1816–1864). ",
       @"Eugene shared a good measure of Gauss's talent in languages and computation.[46] ",
       @"Therese kept house for Gauss until his death, after which she married.",
       @"",
       @"Gauss eventually had conflicts with his sons. He did not want any of his sons to ",
       @"enter mathematics or science for fear of lowering the family name, as he believed ",
       @"none of them would surpass his own achievements.[46] Gauss wanted Eugene to become a ",
       @"lawyer, but Eugene wanted to study languages. They had an argument over a party ",
       @"Eugene held, which Gauss refused to pay for. The son left in anger and, in about ",
       @"1832, emigrated to the United States, where he was quite successful. While working ",
       @"for the American Fur Company in the Midwest, he learned the Sioux language. Later, he ",
       @"moved to Missouri and became a successful businessman. Wilhelm also moved to America ",
       @"in 1837 and settled in Missouri, starting as a farmer and later becoming wealthy in ",
       @"the shoe business in St. Louis. It took many years for Eugene's success to counteract ",
       @"his reputation among Gauss's friends and colleagues. See also the letter from Robert ",
       @"Gauss to Felix Klein on 3 September 1912.",
       @"",
       @"Personality[edit]",
       @"Carl Gauss was an ardent perfectionist and a hard worker. He was never a prolific ",
       @"writer, refusing to publish work which he did not consider complete and above ",
       @"criticism. This was in keeping with his personal motto pauca sed matura (few, but ",
       @"ripe). His personal diaries indicate that he had made several important mathematical ",
       @"discoveries years or decades before his contemporaries published them. ",
       @"Scottish-American mathematician and writer Eric Temple Bell said that if Gauss had ",
       @"published all of his discoveries in a timely manner, he would have advanced ",
       @"mathematics by fifty years.[47]",
       @"",
       @"Though he did take in a few students, Gauss was known to dislike teaching. It is said ",
       @"that he attended only a single scientific conference, which was in Berlin in 1828. ",
       @"However, several of his students became influential mathematicians, among them ",
       @"Richard Dedekind and Bernhard Riemann.",
       @"",
       @"On Gauss's recommendation, Friedrich Bessel was awarded an honorary doctor degree ",
       @"from Göttingen in March 1811.[48] Around that time, the two men engaged in an ",
       @"epistolary correspondence.[49] However, when they met in person in 1825, they ",
       @"quarrelled; the details are unknown.[50]",
       @"",
       @"Before she died, Sophie Germain was recommended by Gauss to receive her honorary ",
       @"degree; she never received it.[51]",
       @"",
       @"Gauss usually declined to present the intuition behind his often very elegant ",
       @"proofs—he preferred them to appear out of thin air and erased all traces of how he ",
       @"discovered them.[citation needed] This is justified, if unsatisfactorily, by Gauss in ",
       @"his Disquisitiones Arithmeticae, where he states that all analysis (i.e., the paths ",
       @"one traveled to reach the solution of a problem) must be suppressed for sake of ",
       @"brevity.",
       @"",
       @"Gauss supported the monarchy and opposed Napoleon, whom he saw as an outgrowth of ",
       @"revolution.",
       @"",
       @"Gauss summarized his views on the pursuit of knowledge in a letter to Farkas Bolyai ",
       @"dated 2 September 1808 as follows:",
       @"",
       @"It is not knowledge, but the act of learning, not possession but the act of getting ",
       @"there, which grants the greatest enjoyment. When I have clarified and exhausted a ",
       @"subject, then I turn away from it, in order to go into darkness again. The ",
       @"never-satisfied man is so strange; if he has completed a structure, then it is not in ",
       @"order to dwell in it peacefully, but in order to begin another. I imagine the world ",
       @"conqueror must feel thus, who, after one kingdom is scarcely conquered, stretches out ",
       @"his arms for others.[52]",
       ];
}

@end
